intial commit
absolunet/github-node-reusable-workflows pull request #1
Opened 2022-06-09 15:25 UTC by absolunet-pleminh

2022-06-09 17:52 UTC, fpoulin09 commented on README.md
> +# workflows/setup.yml@production
Ceci s'applique à chaque section

2022-06-09 17:52 UTC, fpoulin09 commented on README.md
> +```yaml
Mauvais exemple: c'est pas le code du test

2022-06-09 17:52 UTC, fpoulin09 commented on README.md
> +- [A private package to be published on Jfrog Artifactory](#A-private-package-to-be-published-on-Jfrog-Artifactory)
A-t-on vrmt besoin des deux exemple? On explique déjà en haut la différence

2022-06-09 17:52 UTC, fpoulin09 commented on .github/workflows/setup.yml
> +permissions:
On en a parlé vite à matin, mais je voie toujours pas le besoin. Si je veux edit le code c'est pas ça qui va m'en empêcher dans le workflow de mon projet

2022-06-09 17:52 UTC, fpoulin09 commented on .github/workflows/publish.yml
> +          git config --global core.autocrlf false
Pourquoi deja le autocrlf?

2022-06-09 17:52 UTC, fpoulin09 commented on .github/workflows/test.yml
> +    runs-on: ${{ matrix.os }}
? de cohérence: pourquoi mettre une strategy pour l'os alors que dans les autre workflow on le met directement

2022-06-09 21:35 UTC, absolunet-pleminh commented on .github/workflows/publish.yml
> +          git config --global core.autocrlf false
On veut le mettre le autocrlf en false surtout a cause de windows. Lorsque l'on checkout a partir de windows ou que l'on manipule des fichiers, generalement, il transforme les fin de ligne en CRLF. Et puis lors du commit, tous les fichiers sont vu comme `Modified`. 

Peut etre que ce n'est plus utile ici, etant donnee que le checkout se fait toujours sur une machine Linux. Historiquement, je penses que Mel a ajouter ca sur la premiere version, lorsqu'on utiliser le checkout dans une matrice liee aux Systeme d'exploitation pour les tests. 

Mais personnellement, je laisserai le autocrlf a false . Car on ne veut jamais avoir de end-line en CRLF.

2022-06-10 13:42 UTC, fpoulin09 commented on .github/workflows/setup.yml
> +      branch-ref:
Good

2022-06-10 13:45 UTC, fpoulin09 commented on .github/workflows/test.yml
> +    runs-on: ${{ matrix.os }}
Ajouter Windows dans la matrice

2022-06-13 16:42 UTC, absolunet-pleminh commented on .github/workflows/setup.yml
> +permissions:
Comme discute, on enleve les permissions

2022-06-13 16:43 UTC, absolunet-pleminh commented on README.md
> +- [A private package to be published on Jfrog Artifactory](#A-private-package-to-be-published-on-Jfrog-Artifactory)
Done

2022-06-13 21:45 UTC, jblandry requested changes
Question générale ya une raison pourquoi les fichiers sont sous `.github/workflows` s'ils ne sont pas roulés par ce repo comme tel, je les mettrais directement à la racine il me semble que ça ferait plus propore et moins mélangeant.

```yaml
- uses: absolunet/github-node-reusable-workflows/build.yml@production
```

vs

```yaml
- uses: absolunet/github-node-reusable-workflows/.github/workflows/build.yml@production
```

2022-06-13 21:45 UTC, jblandry commented on .github/workflows/test.yml
> +      - name: "Use GNU tar instead BSD tar"
J'enlèverais les `""` c'est la seule place où il y en a

2022-06-14 14:30 UTC, absolunet-pleminh commented on .github/workflows/test.yml
> +      - name: "Use GNU tar instead BSD tar"
Done

2022-06-14 17:35 UTC, Essomia commented on .github/workflows/version_bump.yml
> +          git config --global core.autocrlf false
Je ne suis pas certaine de son utilité ici... 
Au départ, j'avais ajouté cette ligne `git`, car en roulant la commande de test sur une machine `windows`, cela me sortait des erreurs pour la validation des fichiers (crlf vs lf).
Petit rappel, que j'ai désactivé les "vrai" test du manager pour `demo-eslint-config` pour éviter que les workflows prennent mille-ans.

2022-06-14 17:35 UTC, Essomia commented on LICENSE
> +Copyright (c) 2022-2022 Valtech or its affiliates. All rights reserved.
Pas sûr que le 2022-2022 soit utile ici... pour une même année, on ne devrait pas mettre juste 2022

2022-06-14 17:35 UTC, Essomia commented on README.md
> +# GitHub Actions Reusable Workflows for Node.js projects
Si on a retiré le terme "Actions" du nom du repo, je pense qu'on peut le retirer ici :) 
Je pense qu'on va devoir revoir la documentation à un moment pour séparer documentation des flows et documentation sur l'utilisation de ceux-ci.

2022-06-14 17:44 UTC, Essomia commented
> Question générale ya une raison pourquoi les fichiers sont sous `.github/workflows` s'ils ne sont pas roulés par ce repo comme tel, je les mettrais directement à la racine il me semble que ça ferait plus propore et moins mélangeant.
> 
> ```yaml
> - uses: absolunet/github-node-reusable-workflows/build.yml@production
> ```
> 
> vs
> 
> ```yaml
> - uses: absolunet/github-node-reusable-workflows/.github/workflows/build.yml@production
> ```

Hum, ben selon GitHub docs, le dossier recommandé est bien celui des workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows 
Est-ce qu'on voudrait changer cela pour nos standards ?

2022-06-14 19:11 UTC, absolunet-pleminh commented on .github/workflows/version_bump.yml
> +          git config --global core.autocrlf false
Voir discussion ici https://github.com/absolunet/github-node-reusable-workflows/pull/1/files/c66fae690d616853f3367c5347d36bc2fb3194d3#r893981951 

Perso, je le laisserai. On ne veut jamais avoir les end-line en crlf .

2022-06-14 19:11 UTC, jblandry commented
> > Question générale ya une raison pourquoi les fichiers sont sous `.github/workflows` s'ils ne sont pas roulés par ce repo comme tel, je les mettrais directement à la racine il me semble que ça ferait plus propore et moins mélangeant.
> > ```yaml
> > - uses: absolunet/github-node-reusable-workflows/build.yml@production
> > ```
> > vs
> > ```yaml
> > - uses: absolunet/github-node-reusable-workflows/.github/workflows/build.yml@production
> > ```
> 
> Hum, ben selon GitHub docs, le dossier recommandé est bien celui des workflows: [docs.github.com/en/actions/using-workflows/reusing-workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) Est-ce qu'on voudrait changer cela pour nos standards ?

Non c'est bon j'avions pas vu que ça semble être le standard....

2022-06-14 19:23 UTC, absolunet-pleminh commented on README.md
> +# GitHub Actions Reusable Workflows for Node.js projects
Done

2022-06-14 19:44 UTC, Essomia commented on .github/workflows/version_bump.yml
> +          git config --global core.autocrlf false
Je me demande alors si cela a du sens... car on s'entend que ici on roule (runs-on) les commandes git sur un "linux", d'où ma petite question... Il faudrait peut-être le noter en commentaire ou dans la doc le pourquoi du comment...

2022-06-14 19:57 UTC, jblandry commented on LICENSE
> +Copyright (c) 2022-2022 Valtech or its affiliates. All rights reserved.
```suggestion
Copyright (c) 2022 Valtech or its affiliates. All rights reserved.
```

2022-06-14 20:02 UTC, jblandry approved these changes

2022-06-14 20:06 UTC, Essomia commented on .github/workflows/publish.yml
> +      - name: Configure git
```suggestion
      # We use`autocrlf` here to fix flow in case this reusable workflow is use after another one run-on windows.
      - name: Configure git
```

2022-06-14 20:08 UTC, Essomia commented on .github/workflows/version_bump.yml
> +      - name: Configure git
```suggestion
      # We use `autocrlf` here to fix flow in case this reusable workflow is use after another one run-on windows.
      - name: Configure git
```

2022-06-14 20:13 UTC, Essomia approved these changes

2022-06-14 20:16 UTC, merged